FROM python:3.7-alpine

MAINTAINER Screaming_Bunny

LABEL name="Base Alpine Python3" \
vendor="Screaming Bunny" \
license="BSD" \
version="2.0" \
description="This is the Base Alpine Python3 container for Screaming Bunny."

ENV PYTHONUNBUFFERED=0
ENV DOCKERIZE_VERSION v0.6.1

ADD modules/ /tmp/modules
ADD https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz /tmp/dockerize.tar.gz
ADD https://bootstrap.pypa.io/get-pip.py /tmp/get-pip.py

# Package Installation
# Packages - https://pkgs.alpinelinux.org/packages
RUN apk update && \
apk add --no-cache bash && \
apk add shadow && \
apk add dos2unix && \
apk add gcc && \
apk add musl-dev


RUN tar -C /usr/local/bin -xzvf /tmp/dockerize.tar.gz && \
python3 /tmp/get-pip.py && \
pip3 install --upgrade pip && \
cd /tmp/modules/utils && \
python3 setup.py install && \
cd && \
apk del tar && \
rm -rf /var/cache/apk/* *.tar.gz* /usr/src /root/.gnupg /tmp/* && \
python3 --version && \
pip3 --version
